# Generated by Django 4.2.8 on 2023-12-05 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.funcionario', verbose_name='Funcionário que atende'),
        ),
    ]
