# Generated by Django 4.2.8 on 2023-12-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_gerente_alter_cliente_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='apelido',
            field=models.CharField(max_length=255, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='snap',
            field=models.CharField(max_length=255, verbose_name='Instagram'),
        ),
    ]
