# Generated by Django 4.2.8 on 2023-12-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_funcionario_apelido_alter_funcionario_snap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='apelido',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='empresa',
            field=models.CharField(max_length=255, null=True, verbose_name='Empresa'),
        ),
    ]
