# Generated by Django 4.2.8 on 2023-12-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_remove_funcionario_apelido_funcionario_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='snap',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='instagram',
            field=models.CharField(max_length=255, null=True, verbose_name='Instagram'),
        ),
    ]
